spring.application.name=task-manager-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgresql

jwt.secret = 12345678901234567890123456789012